#ifndef _LIMITS_H_
#define _LIMITS_H_

#define INTEREST	.03110
#define COMPOUND_RATE	12
#define PAY_RATE	12
#define LOAN_LENGTH	30 * 12

#define YEARLY_HOME_INSURANCE 0.004
#define YEARLY_PROP_TAXES 0.0069
#define MONTHLY_CAPEX 0.05
#define MONTHLY_VACANCY 0.025
#define MONTHLY_REPAIRS 0.025
#define MONTHLY_MANAGEMENT 0.08
#define MINIMUM_CASH_FLOW_MONTHLY 100
#define DEFAULT_DOWN_PAYMENT .2
#define YEARLY_INCREASE_RENT .03
#define YEARLY_PROP_APP .03
#define YEARLY_FEE_INCREASE .03

#endif
